# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MM
logo: ./assets/images/icons8-calculator.png
email:
author_link: "https://www.justiceo.com/"
author_name: "Justice Ogbonna"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Justice Ogbonna"
  avatar : "/assets/images/author_image.jpg"
  bio    : "I am a Software Engineer by day and entrepreneur by night. I have some experience developing websites and mobile apps and have graced the partnership of startups and small businesses."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.justiceo.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/justice_mode"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/justiceo"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/justice.ogbonna"

footer:
  links:
    - src: "./assets/images/Facebook.svg"
      url: "https://facebook.com/justice.ogb"

    - src: "./assets/images/Twitter Squared.svg"
      url: "https://twitter.com/justice_mode"

    - src: "./assets/images/Instagram Old.svg"
      url: "https://instagram.com/justice.ogbonna"

    - src: "./assets/images/GitHub.svg"
      url: "https://github.com/justiceo"

    - src: "./assets/images/Mail.svg"
      url: "mailto:hello@justiceo.com"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
